const List<String> food = [
  'Burrito',
  'Butifarra',
  'Caballa',
  'Cacahuetes',
  'Cacao',
  'Café',
  'Calabacín',
  'Calabaza',
  'Calamar',
  'Caldo',
  'Camarones',
  'Canelones',
  'Cangrejo',
  'Caqui',
  'Caracol',
  'Carne',
  'Carne de Cerdo',
  'Carne de Conejo',
  'Carne de Cordero',
  'Carne de Vaca',
  'Ternera',
  'Atún',
  'Avellanas',
  'Avena',
  'Azúcar',
  'Bacalao',
  'Budín',
  'Plátanos',
  'Almendras',
  'Batido Chocolate',
  'Avena con leche',
  'Horchata',
  'Bebida deportiva',
  'Bebida energética',
  'Berberechos',
  'Berenjenas',
  'Berro',
  'Besugo',
  'Bígaros',
  'Biscotes',
  'Bombones',
  'Boniato',
  'Brandy',
  'Bratwurst',
  'Pescado Blanco',
  'Brécol',
  'Brócoli',
  'Brotes de soja',
  'Budín de coco',
  'Bullabesa',
  'Buñuelo',
  'Abadejo',
  'Abulón',
  'Asedias Fritas',
  'Aceite de almendras',
  'Aceite de girasol',
  'Aceite de oliva',
  'Aceitunas negras',
  'Aceitunas verdes',
  'Acelgas',
  'Acerolas',
  'Aderezo César',
  'Aderezo de miel y mostaza',
  'Aderezo de queso azul o roquefort',
  'Aderezo de yogurt',
  'Agua carbonatada',
  'Agua Manantial',
  'Aguacate crudo',
  'Ajo',
  'Albahaca',
  'Albaricoques',
  'Alcachofas',
  'Alitas de pollo',
  'Almejas',
  'Alubias',
  'Anacardo',
  'Ancas de rana',
  'Anchoa enlatada',
  'Anguila',
  'Angulas',
  'Anisete',
  'Apio',
  'Arándanos',
  'Arenque',
  'Arroz',
  'Carpa',
  'Castañas',
  'Caviar',
  'Cebada',
  'Cebolla',
  'Cebollino',
  'Centollo',
  'Cereales',
  'Cerezas',
  'Cerveza',
  'Ceviche',
  'Champán',
  'Champiñones',
  'Chanquetes',
  'Cheetos',
  'Chícharos',
  'Chicharrones',
  'Chile',
  'Chili',
  'Chirimoya',
  'Chirivías',
  'Chocolate blanco',
  'Chocolate blanco con almendras',
  'Chocolate con leche',
  'Chocolate puro',
  'Chocolate sin leche',
  'Chorizo',
  'Chuleta de cerdo',
  'Chuleta de ternera',
  'Churros',
  'Cigala',
  'Cilantro',
  'Ciruela',
  'Ciruelas',
  'Coco',
  'Cóctel Bacardí',
  'Codorniz',
  'Col rizada',
  'Coles de Bruselas',
  'Coliflor',
  'Colinabo',
  'Conejo',
  'Congrio',
  'Conguitos',
  'Colas',
  'Corazón Cordero',
  'Corazón Vacuno',
  'Cordero',
  'Corvina',
  'Crema chocolate con avellanas',
  'Crema Leche',
  'Crepes',
  'Croqueta de jamón',
  'Cuajada',
  'Cubitos Sopa',
  'Daiquiri',
  'Dátiles',
  'Diente de león verde',
  'Dorada',
  'Encurtidos',
  'Endibias',
  'Ensalada',
  'Ensalada',
  'Espárragos',
  'Espinacas',
  'Esturión',
  'Extracto de levadura',
  'Lechuga',
  'Lenguado',
  'Lentejas',
  'Levadura',
  'Lichi',
  'Lima',
  'Limón',
  'Lombarda (col lombarda)',
  'Lomo Cerdo',
  'Lubina',
  'Lucio',
  'Macarrones',
  'Magdalena',
  'Maíz',
  'Maíz Dulce',
  'Malvavisco',
  'Mandarina',
  'Mango',
  'Manhattan Cocktail',
  'Manteca de cerdo',
  'Mantequilla',
  'Manzana',
  'Margarina',
  'Martini',
  'Mayonesa',
  'Mazapán',
  'Mejillones',
  'Melocotón',
  'Melocotón en almíbar',
  'Melón',
  'Membrillo',
  'Merluza',
  'Mermelada',
  'Miel',
  'Miso',
  'Molleja',
  'Moras',
  'Morcilla',
  'Mortadela',
  'Mostaza',
  'Mousse de chocolate',
  'Muffin de chocolate',
  'Muslo de pollo',
  'Nabo',
  'Nachos con queso',
  'Naranja',
  'Nectarina',
  'Piña',
  'Piña en almíbar',
  'Pila seca',
  'Pilones',
  'Pipas girasol',
  'Pistachos',
  'Pollo',
  'Melogotón',
  'Pomelo',
  'Ponche de huevo',
  'Postre de gelatina',
  'Pretzel',
  'Puerro',
  'Pulpo',
  'Queso',
  'Quiche Lorraine Bacón-Queso',
  'Rábano crudo',
  'Bananas',
  'Rabo Vacuno',
  'Rape',
  'Ratatouille',
  'Raviolis Tomate',
  'Harina Soja',
  'Harina Trigo',
  'Helado',
  'Helado Fruta',
  'Hígado Cerdo',
  'Hígado Pollo',
  'Hígado Ternera',
  'Higos',
  'Higos Secos',
  'Hojas de cardo',
  'Huevas de arenque',
  'Huevas de esturión',
  'Huevos',
  'Hummus',
  'Jamón',
  'Judías',
  'Zumo de lima',
  'Zumo de naranja',
  'Zumo de pomelo',
  'Zumo de apio',
  'Zumo de arándano',
  'Zumo de ciruela',
  'Zumo de coco',
  'Zumo de fresa',
  'Zumo de granada',
  'Zumo de lima',
  'Zumo de limón',
  'Zumo de mandarina',
  'Zumo de manzana',
  'Zumo de maracuyá',
  'Zumo de mora',
  'Zumo de naranja',
  'Zumo de papaya',
  'Zumo de pila',
  'Zumo de sandia',
  'Zumo de tomate',
  'Zumo de uva',
  'Zumo de zanahoria',
  'Jurel',
  'Kéfir',
  'Kétchup',
  'Kiwi crudo',
  'Langosta',
  'Langostino',
  'Leche sin lactosa',
  'Leche',
  'Nueces',
  'Nuggets de pollo',
  'Ñoquis',
  'Orejas de cerdo',
  'Ostras crudas',
  'Paella',
  'Palmitos enlatados (conserva)',
  'Paloma',
  'Palometa (pescado)',
  'Palomitas',
  'Palosanto',
  'Pan',
  'Papaya',
  'Pasas',
  'Pastrami',
  'Patas de pollo',
  'Patatas',
  'Patatas fritas',
  'Pato',
  'Pavo',
  'Pepinillos en vinagre',
  'Pepino',
  'Pera',
  'Perca',
  'Percebes',
  'Perdiz',
  'Perejil',
  'Pescadilla',
  'Petit-Suisse Queso',
  'Pez espada',
  'Pichón',
  'Pimiento',
  'Pila',
  'Sepia',
  'Sesos Cerdo',
  'Sesos Cordero',
  'Sesos Ternera',
  'Setas',
  'Seven-Up',
  'Sidra de manzana',
  'Soja',
  'Sorbete de cítrico',
  'Sorbete',
  'Stroganoff de jamón',
  'Strudel de manzana',
  'Sushi',
  'Tamarindo',
  'Tapioca',
  'Tarta de Manzana',
  'Té',
  'Tequila',
  'Toblerone',
  'Tocino',
  'Tomates',
  'Tónica',
  'Tortilla de clara de huevo',
  'Tortilla de huevo o huevo revuelto',
  'Tortilla de maíz',
  'Trucha',
  'Trufas',
  'Melón',
  'Turrón Media',
  'TWIX Barras de galletas de caramelo',
  'Uvas',
  'Uvas Pasas',
  'Vermut Seco',
  'Vieiras',
  'Vinagre',
  'Vino',
  'Vodka',
  'Whisky',
  'Yogur',
  'Refresco cola',
  'Regaliz',
  'Remolachas',
  'Repollo',
  'Requesón',
  'Riñón cocido',
  'Rodaballo',
  'Ron',
  'Sandía',
  'Ruibarbo crudo',
  'Sal',
  'Salami',
  'Salchichas Cerdo',
  'Salchichas Fráncfort',
  'Salchichón',
  'Salmón',
  'Salmonete',
  'Salsa',
  'Golosinas',
  'Cucherías',
  'Salvado de avena',
  'Salvado de trigo',
  'Sandía cruda',
  'Sangre Vacuno',
  'Sangría blanca',
  'Sangría roja',
  'Sardinas',
  'Semillas de chía',
  'Semillas de girasol',
  'Semillas de sésamo',
  'Sémola',
  'Yogurt',
  'Yuca fritas',
  'Zanahorias',
  'Faisán cocinado',
  'Faneca (pescado blanco)',
  'Filete',
  'Flan de huevo',
  'Fletán',
  'Foie-Gras',
  'Frambuesas',
  'Frankfurter',
  'Fresas',
  'Frijol mungo sin grasa añadida en la cocción',
  'Frijoles',
  'Galletas saladas',
  'Galletas',
  'Gallo',
  'Gambas al ajillo',
  'Gambas',
  'Ganso',
  'Garbanzos',
  'Gatorade',
  'Gazpacho',
  'Germen de trigo',
  'Gin tonic',
  'Ginebra',
  'Gofio Millo',
  'Gofio Trigo',
  'Granada',
  'Grelos',
  'Grosellas',
  'Guisantes',
  'Habas secas',
  'Hamburguesas',
  'Harina de Avena',
  'Harina de Centeno',
  'Harina de Maíz'
];
