const List<String> food = [
'Burrito',
'Butifarra',
'Caballa',
'Cacahuetes',
'Cacao',
'Café',
'Calabacín',
'Calabaza',
'Calamar',
'Caldo',
'Camarones',
'Canelones',
'Cangrejo',
'Caqui',
'Caracol',
'Carne de Cerdo',
'Carne de Conejo',
'Carne de Cordero',
'Ternera',
'Carne de Vaca',
'Atún',
'Avellanas',
'Avena',
'Azúcar',
'Bacalao',
'Budín',
'Platanos',
'Almendras',
'Batido Chocolate',
'Batido de leche',
'Bebida de avena con leche',
'Horchata',
'Bebida deportiva',
'Bebida energética',
'Berberechos Cocidos',
'Berenjena cruda',
'Berenjenas',
'Berro',
'Berro',
'Besugo',
'Bígaros Cocidos',
'Biscotes Trigo',
'Biscotes Trigo Integrales',
'Bloody Mary',
'Bollos-Pastas Media',
'Bombones Media',
'Boniato',
'Brandy',
'Bratwurst',
'Breca (pescado blanco)',
'Brécol crudo',
'Brócoli crudo',
'Brócoli',
'Brotes de soja',
'Brotes de soja',
'Budín de coco',
'Bullabesa',
'Buñuelo francés',
'Buñuelo',
'Buñuelos de bacalao',
'Buñuelos de maíz',
'Abadejo',
'Abulón',
'Asedias Fritas',
'Aceite de almendras',
'Aceite de cacahuete',
'Aceite de coco',
'Aceite de girasol',
'Aceite de maíz',
'Aceite de nuez',
'Aceite de oliva',
'Aceite de sésamo',
'Aceite de soja',
'Aceite Uva',
'Aceitunas negras',
'Aceitunas verdes',
'Aceitunas verdes rellenas',
'Acelga cruda',
'Acerolas',
'Aderezo César',
'Aderezo de miel y mostaza',
'Aderezo de queso azul o roquefort',
'Aderezo de yogurt',
'Agua carbonatada',
'Agua Manantial',
'Aguacate crudo',
'Ajo crudo',
'Albahaca cruda',
'Albaricoque crudo',
'Albaricoque',
'Albaricoque',
'Albóndigas suecas con crema o salsa blanca',
'Alcachofa',
'Alcachofa',
'Alcachofas',
'Alitas de pollo',
'Almejas crudas/Chirla',
'Almejas enlatadas',
'Almendras saladas',
'Almendras sin sal',
'Almendras sin tostar',
'Alubias blancas',
'Anacardo',
'Ancas de rana',
'Anchoa enlatada',
'Anguila',
'Anguila ahumada',
'Anguila al vapor o escalfada',
'Angulas',
'Anisete',
'Apio cocido',
'Apio crudo',
'Arándanos crudos',
'Arándanos secos',
'Arenque crudo',
'Arenque Seco',
'Arenque',
'Arroz cocido con leche',
'Arroz Integral',
'Arroz Pulido',
'Arroz',
'Arroz',
'Arroz',
'Carne Vaca',
'Carne Vaca',
'Carne Vaca',
'Carpa ahumada',
'Carpa al vapor o escalfado',
'Carpa',
'Castañas',
'Caviar Ruso',
'Cebada',
'Cebolla',
'Cebollino crudo',
'Centollo',
'Cerdo',
'Cereal',
'Cereales Cornflakes',
'Cereales',
'Cerezas',
'Cerezas congeladas',
'Cerveza',
'Cerveza baja en carbohidratos',
'Ceviche',
'Champán',
'Champiñones crudos',
'Champiñones',
'Champiñones',
'Chanquetes',
'Cheetos Queso',
'Chícharos',
'Chicharrones',
'Chile con frijoles sin carne',
'Chili con carne con frijoles',
'Chirimoya',
'Chirivías',
'Chirivías',
'Chocolate blanco',
'Chocolate blanco con almendras',
'Chocolate con leche',
'Chocolate dulce u oscuro',
'Chocolate dulce u oscuro',
'Chocolate sin leche',
'Chorizo',
'Chorizo de ternera con queso',
'Chuleta de cerdo',
'Chuleta de cerdo',
'Chuleta de cerdo',
'Chuleta de cerdo',
'Chuleta de cerdo',
'Chuleta de ternera frita',
'Chuleta de ternera',
'Churros',
'Cigala',
'Cilantro crudo',
'Ciruela cruda',
'Ciruelas pasas',
'Coco fresco',
'Cóctel Bacardí',
'Codorniz',
'Col rizada',
'Coles de Bruselas',
'Coles de Bruselas',
'Coliflor cocida',
'Coliflor cruda',
'Coliflor rebozada',
'Colinabo crudo',
'Conejo guisado',
'Conejo',
'Congrio',
'Conguitos',
'Colas',
'Corazón Cordero',
'Corazón Vacuno',
'Cordero',
'Cordero',
'Cordero',
'Cordero',
'Cortezas de piel de cerdo',
'Corvina',
'Corvina',
'Crema chocolate con avellanas',
'Crema Leche',
'Crepe',
'Croissant',
'Croissant',
'Croqueta de jamón',
'Cuajada',
'Cubitos Sopa',
'Daiquiri',
'Dátiles',
'Diente de león verde',
'Dorada',
'Emperador',
'Emperador a la plancha',
'Encurtidos',
'Endibias',
'Ensalada César de pollo o pavo lechuga',
'Ensalada César',
'Ensalada de atún con huevo',
'Ensalada de atún con queso',
'Espárragos cocidos',
'Espárragos crudos',
'Espárragos Enlatados (Conserva)',
'Espinacas cocidas',
'Espinacas crema fresca',
'Espinacas crudas',
'Esturión ahumado',
'Esturión al vapor',
'Extracto de levadura para untar',
'Leche Entera',
'Leche evaporada entera',
'Leche evaporada',
'Leche sin lactosa',
'Lechuga cruda',
'Lechuga romana cruda',
'Lechuga',
'Lechuga',
'Lenguado',
'Lentejas secas',
'Lentejas',
'Levadura',
'Levadura de Cerveza',
'Lichi crudo',
'Lima cruda',
'Limón crudo',
'Lombarda (col lombarda)',
'Lomo Cerdo Embuchado',
'Lubina al vapor o escalfado',
'Lucio al vapor o escalfado',
'Macarrones',
'Magdalena',
'Maíz al horno',
'Maíz crudo',
'Maíz Dulce Mazorca',
'Malvavisco',
'Mandarina cruda',
'Mango crudo',
'Manhattan Cocktail',
'Manteca de cerdo',
'Mantequilla',
'Manzana cruda',
'Manzana',
'Margarina',
'Martini',
'Mayonesa',
'Mayonesa',
'Mazapán',
'Mejillones al vapor o escalfados',
'Mejillones crudos',
'Melocotón crudo',
'Melocotón en almíbar',
'Melón',
'Membrillo (dulce de)',
'Merluza',
'Mermelada',
'Miel',
'Miso',
'Molleja',
'Moras congeladas',
'Moras crudas',
'Morcilla',
'Mortadela',
'Mostaza',
'Mousse de chocolate',
'Muffin de chocolate',
'Muslo de pollo',
'Muslo de pollo',
'Nabo crudo',
'Nachos con queso',
'Naranja',
'Nectarina',
'Piña en almíbar',
'Pila seca',
'Pilones',
'Pipas girasol',
'Pistachos',
'Plátano crudo',
'Pollo',
'Pollo (con piel)',
'Pollo o pavo agridulce',
'Pollo',
'Pollo',
'Pollo',
'Pomelo crudo',
'Ponche de huevo',
'Postre de gelatina',
'Pretzel',
'Puerro crudo',
'Pulpo hervido',
'Queso americano',
'Queso Azul',
'Queso Babibel',
'Queso Blanco Desnatado',
'Queso Brie',
'Queso Burgos',
'Queso Cabra',
'Queso Camembert',
'Queso Cheddar',
'Queso Chihuahua',
'Queso Colby',
'Queso con nueces',
'Queso Cotija',
'Queso crema',
'Queso de cabra',
'Queso Emmental',
'Queso Feta',
'Queso Fontina',
'Queso Fresco (de Burgos)',
'Queso Gouda o Edam',
'Queso Gruyere',
'Queso Limburger',
'Queso Manchego Curado',
'Queso Manchego Fresco',
'Queso Manchego Semicurado',
'Queso Monterey',
'Queso Mozzarella',
'Queso Münster',
'Queso parmesano',
'Queso Pirineos',
'Queso Porciones',
'Queso Port du Salut',
'Queso Provolone',
'Queso Quark',
'Queso Ricota',
'Queso Roquefort',
'Queso Suizo',
'Queso tipo Speisequark',
'Quiche Lorraine Bacón-Queso',
'Rábano crudo',
'Rabo Vacuno',
'Rape',
'Ratatouille',
'Raviolis Tomate',
'Harina Soja',
'Harina Trigo',
'Harina Trigo',
'Helado',
'Helado Fruta',
'Hígado Cerdo',
'Hígado Pollo',
'Hígado Ternera',
'Higos',
'Higos Secos',
'Hojas de cardo',
'Huevas de arenque',
'Huevas de esturión',
'Huevo Duro',
'Huevo entero crudo',
'Huevo entero frito con aceite.',
'Huevo',
'Huevo',
'Hummus',
'Jamón Cocido',
'Jamón de pavo',
'Jamón serrano',
'Jamón',
'Jamón',
'Judías blancas secas/Alubias blancas secas',
'Jugo/Zumo de apio',
'Jugo / Zumo de arándano',
'Jugo / Zumo de ciruela',
'Jugo / Zumo de coco',
'Jugo / Zumo de fresa',
'Jugo / Zumo de granada',
'Jugo / Zumo de lima',
'Jugo / Zumo de limón',
'Jugo / Zumo de mandarina',
'Jugo / Zumo de manzana',
'Jugo / Zumo de maracuyá',
'Jugo / Zumo de mora',
'Jugo / Zumo de naranja',
'Jugo / Zumo de papaya',
'Jugo / Zumo de pila',
'Jugo / Zumo de sandia',
'Jugo / Zumo de tomate',
'Jugo / Zumo de uva',
'Jugo / Zumo de zanahoria',
'Jurel',
'Kéfir',
'Kétchup',
'Kiwi crudo',
'Langosta',
'Langostino',
'Leche baja en grasa (1%) semidesnatada',
'Leche baja en grasa (2%) semidesnatada',
'Leche condensada',
'Leche de almendras',
'Leche de almendras',
'Leche de arroz',
'Leche de cabra entera',
'Leche de coco para cocinar',
'Leche de soja',
'Leche desnatada / descremada',
'Leche entera',
'Leche entera con calcio',
'Nueces (castellanas)',
'Nueces de Brasil',
'Nueces de macadamia',
'Nueces Pacanas- Pacanas',
'Nuggets de pollo',
'Ñoquis',
'Orejas de cerdo',
'Ostras crudas',
'Paella con mariscos',
'Paella de carne al estilo valenciano',
'Palmitos enlatados (conserva)',
'Paloma',
'Paloma',
'Palometa (pescado)',
'Palomitas de maíz',
'Palomitas de maíz',
'Palosanto',
'Pan blanco',
'Pan blanco',
'Pan centeno',
'Pan de nuez',
'Pan francés o viena',
'Pan francés o viena',
'Pan integral',
'Pan multigrano',
'Pan pita',
'Pan sin gluten',
'Pan',
'Papaya cruda',
'Pasas',
'Pasta cocida',
'Pasta con sabores',
'Pasta de wasabi',
'Pasta sin gluten',
'Pastrami',
'Patas de pollo',
'Patata asada',
'Patata hervida',
'Patatas fritas',
'Patatas guisadas',
'Patatas puré',
'Pato asado',
'Pavo',
'Pepinillos en vinagre',
'Pepino crudo',
'Pera cruda',
'Perca de mar',
'Perca del océano',
'Perca del océano',
'Percebes',
'Perdiz',
'Perejil crudo',
'Perrito-Caliente Con Mostaza',
'Pescadilla',
'Petit-Suisse Queso',
'Pez espada',
'Pez espada',
'Pichón',
'Pimiento',
'Pimientos en vinagre',
'Pila colada',
'Pila cruda',
'Sepia',
'Sesos Cerdo',
'Sesos Cordero',
'Sesos Ternera',
'Setas Boletus',
'Setas Cantharellus',
'Setas Colmenilla',
'Seven-Up',
'Sidra de manzana',
'Soja Brotes',
'Soja Germinada',
'Sopa agridulce',
'Sopa De Cebolla',
'Sopa Minestrone',
'Sorbete de cítrico',
'Sorbete',
'Stroganoff de jamón',
'Strudel de manzana',
'Sushi',
'Sushi con atún',
'Sushi con salmón',
'Tamarindo',
'Tapioca',
'Tarta Manzana Casera',
'Té caliente a base de hierbas',
'Té caliente',
'Té',
'Tequila',
'Toblerone',
'Tocino',
'Tomate Frito',
'Tomate triturado',
'Tomates cocidos',
'Tomates crudos',
'Tomates rojos secos',
'Tomates verdes crudos',
'Tónica Agua',
'Tortilla de clara de huevo',
'Tortilla de huevo o huevo revuelto',
'Tortilla de maíz',
'Trucha',
'Trucha ahumada',
'Trucha al horno pasada',
'Trufas',
'Turrón Media',
'TWIX Barras de galletas de caramelo',
'Uvas',
'Uvas Pasas',
'Vermut Seco',
'Vieiras al vapor o hervidas',
'Vinagre',
'Vino de arroz',
'Vino Oporto',
'Vino sin alcohol',
'Vino',
'Vino',
'Vino',
'Vodka',
'Whisky',
'Yogur',
'Yogur',
'Yogur',
'Refresco cola',
'Refresco cola light / diet',
'Regaliz',
'Remolachas crudas',
'Remolachas',
'Repollo',
'Repollo',
'Requesón',
'Riñón cocido',
'Rodaballo',
'Ron',
'Ruibarbo crudo',
'Sal',
'Salami',
'Salchichas Cerdo',
'Salchichas Fráncfort',
'Salchichón',
'Salmón ahumado',
'Salmón al vapor o escalfado',
'Salmón crudo',
'Salmonete crudo',
'Salsa Boloñesa',
'Salsa César',
'Salsa de Ajo',
'Salsa de arándano y frambuesa',
'Salsa de barbacoa',
'Salsa de cebolla',
'Salsa de chocolate',
'Salsa de ciruela',
'Salsa de cóctel',
'Salsa de enchilada roja',
'Salsa de enchilada',
'Salsa de eneldo',
'Salsa de miel y mostaza',
'Salsa de pescado',
'Salsa de queso',
'Salsa de queso azul o roquefort',
'Salsa de soja',
'Salsa de tomate',
'Salsa de yogurt',
'Salsa holandesa',
'Salsa Kétchup',
'Salsa pesto',
'Salsa rusa',
'Salsa tártara',
'Salsa teriyaki',
'Salsa Tzatziki',
'Salsa verde o salsa verde',
'Salvado de avena',
'Salvado de trigo',
'Sandía cruda',
'Sangre Vacuno',
'Sangría blanca',
'Sangría roja',
'Sardinas cocidas',
'Sardinas con salsa de tomate',
'Sardinas enlatadas en aceite',
'Sardinas secas',
'Semillas de chía',
'Semillas de girasol',
'Semillas de sésamo',
'Sémola',
'Yogurt liquido',
'Yogurt',
'Yogurt',
'Yogurt',
'Yogurt',
'Yogurt',
'Yuca fritas',
'Zanahorias crudas',
'Zanahorias',
'Zanahorias',
'Zumo de lima',
'Zumo de naranja',
'Zumo de pomelo',
'Faisán cocinado',
'Faneca (pescado blanco)',
'Filete de pollo a la parrilla',
'Filete de pollo empanado',
'Filete o chuleta de cerdo',
'Filete o chuleta de cerdo',
'Filete suizo',
'Filete Vaca',
'Flan de huevo',
'Fletán crudo',
'Fletán',
'Foie-Gras',
'Frambuesas',
'Frambuesas',
'Frankfurter',
'Fresas congeladas',
'Fresas crudas',
'Frijol mungo sin grasa añadida en la cocción',
'Frijoles amarillo sin agregar grasa al cocinar',
'Frijoles blancos sin grasa añadida en la cocción',
'Frijoles de lima sin grasa añadida en la cocción',
'Frijoles mexicanos pintos sin grasa añadida en la cocción',
'Frijoles negros',
'Frijoles rojos sin grasa añadida en la cocción',
'Frijoles rosados sin grasa añadida en la cocción',
'Frijoles verdes cocidos',
'Galleta coco',
'Galleta de mantequilla',
'Galleta jengibre',
'Galleta',
'Galleta',
'Galleta',
'Galletas saladas',
'Gallo',
'Gambas al ajillo',
'Gambas cocidas',
'Ganso',
'Garbanzos sin grasa añadida en la cocción',
'Gatorade',
'Gazpacho',
'Germen de trigo',
'Gin tonic',
'Ginebra',
'Gofio Millo',
'Gofio Trigo',
'Granada',
'Grelos',
'Grosellas crudas',
'Guisantes enlatados (conserva)',
'Guisantes',
'Habas secas',
'Hamburguesas',
'Harina Avena',
'Harina Centeno',
'Harina Maíz',
];