const List<String> food = [
  'Burrito',
  'Butifarra',
  'Caballa',
  'Cacahuetes',
  'Cacao',
  'Café',
  'Calabacín',
  'Calabaza',
  'Calamar',
  'Caldo',
  'Camarones',
  'Canelones',
  'Cangrejo',
  'Caqui',
  'Caracol',
  'Carne',
  'Carne de Cerdo',
  'Carne de Conejo',
  'Carne de Cordero',
  'Carne de Vaca',
  'Ternera',
  'Atún',
  'Avellanas',
  'Avena',
  'Azúcar',
  'Bacalao',
  'Budín',
  'Plátanos',
  'Almendras',
  'Batido Chocolate',
  'Avena con leche',
  'Horchata',
  'Bebida deportiva',
  'Bebida energética',
  'Berberechos',
  'Berenjenas',
  'Berro',
  'Besugo',
  'Bígaros',
  'Biscotes',
  'Bombones',
  'Boniato',
  'Brandy',
  'Bratwurst',
  'Pescado Blanco',
  'Brécol',
  'Brócoli',
  'Brotes de soja',
  'Budín de coco',
  'Bullabesa',
  'Buñuelo',
  'Abadejo',
  'Abulón',
  'Asedias Fritas',
  'Aceite de almendras',
  'Aceite de girasol',
  'Aceite de oliva',
  'Aceitunas negras',
  'Aceitunas verdes',
  'Acelgas',
  'Acerolas',
  'Aderezo César',
  'Aderezo de miel y mostaza',
  'Aderezo de queso azul o roquefort',
  'Aderezo de yogurt',
  'Agua carbonatada',
  'Agua Manantial',
  'Aguacate crudo',
  'Ajo',
  'Albahaca',
  'Albaricoques',
  'Alcachofas',
  'Alitas de pollo',
  'Almejas',
  'Alubias',
  'Anacardo',
  'Ancas de rana',
  'Anchoa enlatada',
  'Anguila',
  'Angulas',
  'Anisete',
  'Apio',
  'Arándanos',
  'Arenque',
  'Arroz',
  'Carpa',
  'Castañas',
  'Caviar',
  'Cebada',
  'Cebolla',
  'Cebollino',
  'Centollo',
  'Cereales',
  'Cerezas',
  'Cerveza',
  //'Cerveza baja en carbohidratos',
  'Ceviche',
  'Champán',
  'Champiñones',
  'Chanquetes',
  'Cheetos',
  'Chícharos',
  'Chicharrones',
  'Chile',
  'Chili',
  'Chirimoya',
  'Chirivías',
  'Chocolate blanco',
  'Chocolate blanco con almendras',
  'Chocolate con leche',
  'Chocolate puro',
  'Chocolate sin leche',
  'Chorizo',
  'Chuleta de cerdo',
  'Chuleta de ternera',
  'Churros',
  'Cigala',
  'Cilantro',
  'Ciruela',
  'Ciruelas',
  'Coco',
  'Cóctel Bacardí',
  'Codorniz',
  'Col rizada',
  'Coles de Bruselas',
  'Coliflor',
  'Colinabo',
  'Conejo',
  'Congrio',
  'Conguitos',
  'Colas',
  'Corazón Cordero',
  'Corazón Vacuno',
  'Cordero',
  'Corvina',
  'Crema chocolate con avellanas',
  'Crema Leche',
  'Crepes',
  'Croqueta de jamón',
  'Cuajada',
  'Cubitos Sopa',
  'Daiquiri',
  'Dátiles',
  'Diente de león verde',
  'Dorada',
  'Encurtidos',
  'Endibias',
  'Ensalada',
  'Ensalada',
  'Espárragos',
  'Espinacas',
  'Esturión',
  'Extracto de levadura',
  'Lechuga',
  'Lenguado',
  'Lentejas',
  'Levadura',
  'Lichi',
  'Lima',
  'Limón',
  'Lombarda (col lombarda)',
  'Lomo Cerdo',
  'Lubina',
  'Lucio',
  'Macarrones',
  'Magdalena',
  'Maíz',
  'Maíz Dulce',
  'Malvavisco',
  'Mandarina',
  'Mango',
  'Manhattan Cocktail',
  'Manteca de cerdo',
  'Mantequilla',
  'Manzana',
  'Margarina',
  'Martini',
  'Mayonesa',
  'Mazapán',
  'Mejillones',
  'Melocotón',
  'Melocotón en almíbar',
  'Melón',
  'Membrillo',
  'Merluza',
  'Mermelada',
  'Miel',
  'Miso',
  'Molleja',
  'Moras',
  'Morcilla',
  'Mortadela',
  'Mostaza',
  'Mousse de chocolate',
  'Muffin de chocolate',
  'Muslo de pollo',
  'Nabo',
  'Nachos con queso',
  'Naranja',
  'Nectarina',
  'Piña',
  'Piña en almíbar',
  'Pila seca',
  'Pilones',
  'Pipas girasol',
  'Pistachos',
  'Pollo',
  'Melogotón',
  'Pomelo',
  'Ponche de huevo',
  'Postre de gelatina',
  'Pretzel',
  'Puerro',
  'Pulpo',
  'Queso',
/*'Queso americano',
'Queso Azul',
'Queso Babibel',
'Queso Blanco Desnatado',
'Queso Brie',
'Queso Burgos',
'Queso Cabra',
'Queso Camembert',
'Queso Cheddar',
'Queso Chihuahua',
'Queso Colby',
'Queso con nueces',
'Queso Cotija',
'Queso crema',
'Queso de cabra',
'Queso Emmental',
'Queso Feta',
'Queso Fontina',
'Queso Fresco (de Burgos)',
'Queso Gouda o Edam',
'Queso Gruyere',
'Queso Limburger',
'Queso Manchego Curado',
'Queso Manchego Fresco',
'Queso Manchego Semicurado',
'Queso Monterey',
'Queso Mozzarella',
'Queso Münster',
'Queso parmesano',
'Queso Pirineos',
'Queso Porciones',
'Queso Port du Salut',
'Queso Provolone',
'Queso Quark',
'Queso Ricota',
'Queso Roquefort',
'Queso Suizo',
'Queso tipo Speisequark', */
  'Quiche Lorraine Bacón-Queso',
  'Rábano crudo',
  'Bananas',
  'Rabo Vacuno',
  'Rape',
  'Ratatouille',
  'Raviolis Tomate',
  'Harina Soja',
  'Harina Trigo',
  'Helado',
  'Helado Fruta',
  'Hígado Cerdo',
  'Hígado Pollo',
  'Hígado Ternera',
  'Higos',
  'Higos Secos',
  'Hojas de cardo',
  'Huevas de arenque',
  'Huevas de esturión',
  'Huevos',
  'Hummus',
  'Jamón',
  'Judías',
  'Zumo de lima',
  'Zumo de naranja',
  'Zumo de pomelo',
  'Zumo de apio',
  'Zumo de arándano',
  'Zumo de ciruela',
  'Zumo de coco',
  'Zumo de fresa',
  'Zumo de granada',
  'Zumo de lima',
  'Zumo de limón',
  'Zumo de mandarina',
  'Zumo de manzana',
  'Zumo de maracuyá',
  'Zumo de mora',
  'Zumo de naranja',
  'Zumo de papaya',
  'Zumo de pila',
  'Zumo de sandia',
  'Zumo de tomate',
  'Zumo de uva',
  'Zumo de zanahoria',
  'Jurel',
  'Kéfir',
  'Kétchup',
  'Kiwi crudo',
  'Langosta',
  'Langostino',
  /* 'Leche baja en grasa',
  'Leche condensada',
  'Leche de almendras',
  'Leche de arroz',
  'Leche de cabra entera',
  'Leche de coco para cocinar',
  'Leche de soja',
  'Leche desnatada',
  'Leche entera',
  'Leche evaporada', */
  'Leche sin lactosa',
  'Leche',
  'Nueces',
/* 'Nueces (castellanas)',
'Nueces de Brasil',
'Nueces de macadamia',
'Nueces Pacanas- Pacanas', */
  'Nuggets de pollo',
  'Ñoquis',
  'Orejas de cerdo',
  'Ostras crudas',
  'Paella',
  'Palmitos enlatados (conserva)',
  'Paloma',
  'Palometa (pescado)',
  'Palomitas',
  'Palosanto',
/* 'Pan blanco',
'Pan centeno',
'Pan de nuez',
'Pan francés o viena',
'Pan integral',
'Pan multigrano',
'Pan pita',
'Pan sin gluten', */
  'Pan',
  'Papaya',
  'Pasas',
/* 'Pasta cocida',
'Pasta con sabores',
'Pasta de wasabi',
'Pasta sin gluten', */
  'Pastrami',
  'Patas de pollo',
  'Patatas',
  'Patatas fritas',
/* 'Patata asada',
'Patata hervida',
'Patatas guisadas',
'Patatas puré', */
  'Pato',
  'Pavo',
  'Pepinillos en vinagre',
  'Pepino',
  'Pera',
  'Perca',
/* 'Perca de mar',
'Perca del océano',
'Perca del océano', */
  'Percebes',
  'Perdiz',
  'Perejil',
//'Perrito-Caliente Con Mostaza',
  'Pescadilla',
  'Petit-Suisse Queso',
  'Pez espada',
  'Pichón',
  'Pimiento',
  'Pila',
  'Sepia',
  'Sesos Cerdo',
  'Sesos Cordero',
  'Sesos Ternera',
  'Setas'
/* 'Setas Boletus',
'Setas Cantharellus',
'Setas Colmenilla', */
      'Seven-Up',
  'Sidra de manzana',
  'Soja',
/* 'Soja Brotes',
'Soja Germinada',
'Sopa agridulce',
'Sopa De Cebolla',
'Sopa Minestrone', */
  'Sorbete de cítrico',
  'Sorbete',
  'Stroganoff de jamón',
  'Strudel de manzana',
  'Sushi',
/* 'Sushi con atún',
'Sushi con salmón', */
  'Tamarindo',
  'Tapioca',
  'Tarta de Manzana',
/* 'Té caliente a base de hierbas',
'Té caliente', */
  'Té',
  'Tequila',
  'Toblerone',
  'Tocino',
  'Tomates',
/* 'Tomate Frito',
'Tomate triturado',
'Tomates cocidos',
'Tomates crudos',
'Tomates rojos secos',
'Tomates verdes crudos', */
  'Tónica',
  'Tortilla de clara de huevo',
  'Tortilla de huevo o huevo revuelto',
  'Tortilla de maíz',
  'Trucha',
  'Trufas',
  'Melón',
  'Turrón Media',
  'TWIX Barras de galletas de caramelo',
  'Uvas',
  'Uvas Pasas',
  'Vermut Seco',
  'Vieiras',
  'Vinagre',
/* 'Vino de arroz',
  'Vino Oporto',
  'Vino sin alcohol', */
  'Vino',
  'Vodka',
  'Whisky',
  'Yogur',
  'Refresco cola',
  'Regaliz',
  'Remolachas',
  'Repollo',
  'Requesón',
  'Riñón cocido',
  'Rodaballo',
  'Ron',
  'Sandía',
  'Ruibarbo crudo',
  'Sal',
  'Salami',
  'Salchichas Cerdo',
  'Salchichas Fráncfort',
  'Salchichón',
  'Salmón',
  'Salmonete',
  'Salsa',
  'Golosinas',
  'Cucherías',
/* 'Salsa Boloñesa',
'Salsa César',
'Salsa de Ajo',
'Salsa de arándano y frambuesa',
'Salsa de barbacoa',
'Salsa de cebolla',
'Salsa de chocolate',
'Salsa de ciruela',
'Salsa de cóctel',
'Salsa de enchilada roja',
'Salsa de enchilada',
'Salsa de eneldo',
'Salsa de miel y mostaza',
'Salsa de pescado',
'Salsa de queso',
'Salsa de queso azul o roquefort',
'Salsa de soja',
'Salsa de tomate',
'Salsa de yogurt',
'Salsa holandesa',
'Salsa Kétchup',
'Salsa pesto',
'Salsa rusa',
'Salsa tártara',
'Salsa teriyaki',
'Salsa Tzatziki',
'Salsa verde o salsa verde', */
  'Salvado de avena',
  'Salvado de trigo',
  'Sandía cruda',
  'Sangre Vacuno',
  'Sangría blanca',
  'Sangría roja',
  'Sardinas'
/* 'Sardinas cocidas',
'Sardinas con salsa de tomate',
'Sardinas enlatadas en aceite',
'Sardinas secas', */
      'Semillas de chía',
  'Semillas de girasol',
  'Semillas de sésamo',
  'Sémola',
  'Yogurt',
  'Yuca fritas',
  'Zanahorias',
  'Faisán cocinado',
  'Faneca (pescado blanco)',
  'Filete'
/* 'Filete de pollo a la parrilla',
'Filete de pollo empanado',
'Filete o chuleta de cerdo',
'Filete o chuleta de cerdo',
'Filete suizo',
'Filete Vaca', */
      'Flan de huevo',
  'Fletán',
  'Foie-Gras',
  'Frambuesas',
  'Frankfurter',
  'Fresas',
  'Frijol mungo sin grasa añadida en la cocción',
  'Frijoles',
/* 'Frijoles amarillo sin agregar grasa al cocinar',
'Frijoles blancos sin grasa añadida en la cocción',
'Frijoles de lima sin grasa añadida en la cocción',
'Frijoles mexicanos pintos sin grasa añadida en la cocción',
'Frijoles negros',
'Frijoles rojos sin grasa añadida en la cocción',
'Frijoles rosados sin grasa añadida en la cocción',
'Frijoles verdes cocidos', */
/* 'Galletas de coco',
'Galletas de mantequilla',
'Galletas de jengibre', */
  'Galletas saladas',
  'Galletas',
  'Gallo',
  'Gambas al ajillo',
  'Gambas',
  'Ganso',
  'Garbanzos',
  'Gatorade',
  'Gazpacho',
  'Germen de trigo',
  'Gin tonic',
  'Ginebra',
  'Gofio Millo',
  'Gofio Trigo',
  'Granada',
  'Grelos',
  'Grosellas',
  'Guisantes',
  'Habas secas',
  'Hamburguesas',
  'Harina de Avena',
  'Harina de Centeno',
  'Harina de Maíz',
];
